# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  desc 'Description of what the lane does'
  lane :build do
    match
    build_app
    upload_ipa
    upload_s3_path
  end
end

def build_app
  ionic(platform: 'ios', type: 'enterprise', team_id: 'K84TL26V3P',
        provisioning_profile: '2b73282a-ccaf-4464-b1fa-eb63a3efe1ee',
        build_flag: ['-UseModernBuildSystem=0'])
  zip(path: './platforms/ios/build/device/Vehicle Testing.app.dSYM')
end

def upload_ipa
  environment = ENV['ENVIRONMENT']
  environment = "feature/#{ENV['BRANCH']}" if environment == 'feature'
  aws_s3(access_key: ENV['AWS_ACCESS_KEY_ID'],
         secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
         bucket: 'dvsa-cvs-mobile-artefacts',
         path: "#{environment}/v{CFBundleShortVersionString}/",
         html_in_folder: true, html_file_name: "#{ENV['BRANCH']}.html",
         region: 'eu-west-1',
         ipa: './platforms/ios/build/device/Vehicle Testing.ipa',
         dsym: './platforms/ios/build/device/Vehicle Testing.app.dSYM.zip')
end

def upload_s3_path
  sh('echo $S3_IPA_OUTPUT_PATH > $BRANCH.txt')
  sh('aws s3 cp $BRANCH.txt s3://dvsa-cvs-mobile-artefacts/files/$BRANCH.txt')
end
